---
apiVersion: compositions.io/v1alpha1
kind: InstanceClaim
metadata:
  name: "cross-ec2"
spec:
  parameters:
    region: "us-east-1"
    ami: "ami-06aa3f7caf3a30282"
    instanceType: "t2.small"
    keyName: "newkey1"
    Name: "cross-ec2"

  compositionRef:
    name: ec2-instance
